baseURL = "http://ibeachnhatrang.com/"
languageCode = "en-us"
title = "iBeach Nha Trang"
theme = "rental"
defaultContentLanguage = "en"

########################################
#
## English
[Languages.en]

# Hero section
[Languages.en.params.hero]
bookNowText = "Book Now"
emailContact = "ibeachnhatrang@gmail.com"
whatsappContact = "+84976466202"
phoneContact = "+84976466202"

logo = "logo.png"
logo_alt = ""
logoIntro = "logo-intro.png"
logoIntro_alt = "iBeach Nha Trang"
logoIntro_desc = "Awesome beach view from awesome apartments"

[Languages.en.params.gallery]
enable = true
title = ""
buttonText = "Learn More"
buttonPath = "#"
    [[Languages.en.params.gallery.slides]]
      img = "gallery-img-1.jpg"
      caption = "Inspiring destinations where you could never build a traditional hotel"
    [[Languages.en.params.gallery.slides]]
      img = "gallery-img-2.jpg"
      caption = "Sleep in luxury and wake up inspired"

[Languages.en.params.features]
enable = true
subtitle = "Featured Apartment"
title = "Hon Chong Apartment"
#quote = ""
featuresHeading = ""
featuresImage = "Header_5.jpg"
featuresDesc = """"""
ctaButton = "View"
ctaButtonPath = "#"

[Languages.en.params.explore]
enable = false

[Languages.en.params.contactCta]
enable = false
text = "Start planning your adventure now."
buttonText = "Contact Us"

[Languages.en.params.footer]
addressTitle = "Address"
address = "Hon Chong Apartments, Nha Trang, Viet Nam"
contactTitle = "Contact"
socialMediaTitle = "Say Hi"
newsletterButtonText = "Get in Touch"
emailPlaceholder = "your email"
[[Languages.en.params.footer.social]]
  text = "Facebook"
  link = "https://www.facebook.com/ibeachnhatrang"
[[Languages.en.params.footer.social]]
  text = "Instagram"
  link = "https://www.instagram.com/ibeachnhatrang/"
  [[Languages.en.params.footer.quicklinks]]
  text = "Terms and Conditions"
  link = "/term-condition"
  [[Languages.en.params.footer.quicklinks]]
  text = "Privacy Policy"
  link = "/privacy-policy"
  [[Languages.en.params.footer.quicklinks]]
  text = "FAQ"
  link = "/faq"
##########################################
[Languages]
#Vietnamese
[Languages.vi]

# Hero section
[Languages.vi.params.hero]
bookNowText = "Đặt Ngay"
logo = "logo.png"
logo_alt = ""
logoIntro = "logo-intro.png"
logoIntro--alt = "iBeach Nha Trang"
logoIntro_desc = "Awesome beach from awesome apartments"

[Languages.vi.params.gallery]
enable = true
title = "A New, Meaningful Way to Travel"
buttonText = "Learn More"
buttonPath = "/learn-more"
    [[Languages.vi.params.gallery.slides]]
      img = "gallery-img-1.jpg"
      caption = "Inspiring destinations where you could never build a traditional hotel"
    [[Languages.vi.params.gallery.slides]]
      img = "gallery-img-2.jpg"
      caption = "Sleep in luxury and wake up inspired"
    [[Languages.vi.params.gallery.slides]]
      img = "gallery-img-3.jpg"
      caption = "World-class chefs bring you seasonal, hyper-local dining under the stars and sky"
    [[Languages.vi.params.gallery.slides]]
      img = "gallery-img-4.jpg"
      caption = "Experience Old World hospitality with modern style and a personal touch"
