baseURL = "http://ibeachnhatrang.com/"
languageCode = "en-us"
title = "iBeach Nha Trang"
theme = "rental"
defaultContentLanguage = "en"

########################################
#
## English
[Languages.en]

# Hero section
[Languages.en.params.hero]
bookNowText = "Book Now"
emailContact = "ibeachnhatrang@gmail.com"
whatsappContact = "+84976466202"
phoneContact = "+84976466202"

logo = "logo.png"
logo_alt = ""
logoIntro = "logo-intro.png"
logoIntro_alt = "iBeach Nha Trang"
logoIntro_desc = "Awesome beach view from awesome apartments"

[Languages.en.params.gallery]
enable = true
title = ""
buttonText = "Learn More"
buttonPath = "#"
    [[Languages.en.params.gallery.slides]]
      img = "slide-2.jpg"
      caption = "Beach view apartments"
    [[Languages.en.params.gallery.slides]]
      img = "slide-1.jpg"
      caption = "5-star grade interior"

[Languages.en.params.features]
enable = true
subtitle = "Featured Apartment"
title = "Hon Chong Apartment"
#quote = ""
featuresHeading = ""
featuresImage = "Header_5.jpg"
featuresDesc = """"""
ctaButton = "View"
ctaButtonPath = "#"

[Languages.en.params.explore]
enable = false

[Languages.en.params.contactCta]
enable = false
text = "Start planning your adventure now."
buttonText = "Contact Us"

[Languages.en.params.footer]
addressTitle = "Address"
address = "Hon Chong Apartments, Nha Trang, Viet Nam"
contactTitle = "Contact"
socialMediaTitle = "Say Hi"
newsletterButtonText = "Get in Touch"
emailPlaceholder = "your email"
[[Languages.en.params.footer.social]]
  text = "Facebook"
  link = "https://www.facebook.com/ibeachnhatrang"
[[Languages.en.params.footer.social]]
  text = "Instagram"
  link = "https://www.instagram.com/ibeachnhatrang/"
  [[Languages.en.params.footer.quicklinks]]
  text = "Terms and Conditions"
  link = "/term-condition"
  [[Languages.en.params.footer.quicklinks]]
  text = "Privacy Policy"
  link = "/privacy-policy"
  [[Languages.en.params.footer.quicklinks]]
  text = "FAQ"
  link = "/faq"
##########################################
[Languages]
#Vietnamese
[Languages.vi]

# Hero section
[Languages.vi.params.hero]
bookNowText = "Đặt Ngay"
emailContact = "ibeachnhatrang@gmail.com"
whatsappContact = "+84976466202"
phoneContact = "+84976466202"

logo = "logo.png"
logo_alt = ""
logoIntro = "logo-intro.png"
logoIntro--alt = "iBeach Nha Trang"
logoIntro_desc = "Căn hộ hướng biển ở Nha Trang"

[Languages.vi.params.gallery]
enable = true
title = "Cách tuyệt vời để tận hưởng Nha Trang"
buttonText = "Tìm Hiểu Thêm"
buttonPath = "/learn-more"
    [[Languages.vi.params.gallery.slides]]
      img = "slide-2.jpg"
      caption = "Căn hộ nhìn thẳng ra biển"
    [[Languages.vi.params.gallery.slides]]
      img = "slide-1.jpg"
      caption = "Tiện nghi nội thất cao cấp tiêu chuẩn 5 sao"

[Languages.vi.params.features]
enable = true
subtitle = "Căn hộ tiêu biểu"
title = "Căn hộ Hòn Chồng"
#quote = ""
featuresHeading = ""
featuresImage = "Header_5.jpg"
featuresDesc = """"""
ctaButton = "Xem"
ctaButtonPath = "#"

[Languages.vi.params.explore]
viable = false

[Languages.vi.params.contactCta]
enable = false
text = "Start planning your adventure now."
buttonText = "Contact Us"

[Languages.vi.params.footer]
addressTitle = "Địa chỉ"
address = "Hon Chong Apartments, Nha Trang, Viet Nam"
contactTitle = "Liên Hệ"
socialMediaTitle = "Ghé Thăm"
newsletterButtonText = "Get in Touch"
emailPlaceholder = "your email"
[[Languages.vi.params.footer.social]]
  text = "Facebook"
  link = "https://www.facebook.com/ibeachnhatrang"
[[Languages.vi.params.footer.social]]
  text = "Instagram"
  link = "https://www.instagram.com/ibeachnhatrang/"
  [[Languages.vi.params.footer.quicklinks]]
  text = "Điều khoản"
  link = "/term-condition"
  [[Languages.vi.params.footer.quicklinks]]
  text = "FAQ"
  link = "/faq"